sudo: false

cache:
  directories:
  - $HOME/.stack

before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
- export PATH=/opt/ghc/7.10.3/bin:$PATH

addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - ghc-7.10.3

language: haskell

ghc:
    - 7.8

install:
    - travis_wait 60 stack --no-terminal --skip-ghc-check setup
    - export PATH=$HOME/.local/bin:$PATH

before_script:
    - true

script:
    - stack --no-terminal --skip-ghc-check install
    - tip-ghc examples/Int.hs
    - tip <(tip-ghc examples/Int.hs)
    - tip-ghc examples/Case.hs
    - tip <(tip-ghc examples/Case.hs)
    - tip-ghc examples/Props.hs
    - tip <(tip-ghc examples/Props.hs)
    - tip examples/simple-monomorphisation.smt2 --monomorphise
