resolver: lts-14.6

packages:
- tip-types/
- tip-lib/
- tip-ghc/
- tip-spec/
- tip-prelude/
extra-deps:
- jukebox-0.3.5
- minisat-0.1.2
- twee-lib-2.1.5
- genifunctors-0.4
- stm-promise-0.0.3.1
- spoon-0.3.1
- testing-feat-1.1.0.0
- tagshare-0.0
- geniplate-mirror-0.7.6
- size-based-0.1.2.0
- testing-type-modifiers-0.1.0.1
- dictionary-sharing-0.1.0.0
- git: git://github.com/nick8325/quickspec
  commit: 5a561f73a20e750337d059d6f7783865ae1cd187
- git: git://github.com/nick8325/structural-induction
  commit: 6128414b8f7324bcfe208a6465fc07df7aa61861
flags:
    tip-spec: {stack: True}
    tip-ghc: {stack: True}
