resolver: lts-6.5
packages:
- tip-haskell-frontend/
- tip-lib/
- tip-spec/
- tip-prelude/
- location:
   git: git://github.com/nick8325/quickspec
   commit: e66f496ef0fa5d5792ef0c3ffe8ebb2c9486f663

extra-deps:
- genifunctors-0.3
- ghc-simple-0.1.3
- jukebox-0.2.7
- minisat-0.1.2
- structural-induction-0.3
- twee-0.1

flags:
    tip-spec: {stack: True}
    tip-haskell-frontend: {stack: True}
