resolver: lts-16.31

packages:
- tip-types/
- tip-lib/
- tip-ghc/
- tip-spec/
- tip-prelude/
extra-deps:
- jukebox-0.3.5
- minisat-0.1.2
- twee-lib-2.4.2
- genifunctors-0.4
- spoon-0.3.1
- testing-feat-1.1.0.0
- tagshare-0.0
- geniplate-mirror-0.7.6
- size-based-0.1.2.0
- testing-type-modifiers-0.1.0.1
- dictionary-sharing-0.1.0.0
- primitive-0.8.0.0
- data-array-byte-0.1.0.1
- git: https://github.com/nick8325/quickspec
  commit: 571b44d10f552075fcd9d7e2933476ff930c4428
- git: https://github.com/nick8325/stm-promise
  commit: 9ef7f1e8797f02b22ae4c8a2f30fda04cfbeb2ba
- git: https://github.com/nick8325/structural-induction
  commit: 6128414b8f7324bcfe208a6465fc07df7aa61861
flags:
    tip-spec: {stack: True}
    tip-ghc: {stack: True}
allow-newer: True
