resolver: lts-7.7

packages:
- tip-types/
- tip-lib/
- tip-ghc/
- tip-spec/
- tip-prelude/
- location:
    git: git://github.com/nick8325/quickspec
    commit: fa14f6749cc37e32a1d5b67a0f1428c159463611

extra-deps:
- jukebox-0.2.10
- minisat-0.1.2
- structural-induction-0.3
- twee-0.1
- genifunctors-0.4

flags:
    tip-spec: {stack: True}
    tip-ghc: {stack: True}
