resolver: lts-6.5
packages:
- tip-haskell-frontend/
- tip-lib/
- tip-spec/
- tip-prelude/
- location:
    git: git://github.com/nick8325/quickspec
    commit: b71f6405e75b545e41c3d0e38f4d4a9b46f4739f

extra-deps:
- genifunctors-0.3
- ghc-simple-0.1.3
- jukebox-0.2.7
- minisat-0.1.2
- structural-induction-0.3
- twee-0.1

flags:
    tip-spec: {stack: True}
    tip-haskell-frontend: {stack: True}
