resolver: lts-6.5
packages:
- tip-haskell-frontend/
- tip-lib/
- tip-spec/
- tip-prelude/
- location:
    git: git://github.com/nick8325/quickspec
    commit: c63e13992fc3b25909b108eca663e7f7ea7184b2

extra-deps:
- genifunctors-0.3
- ghc-simple-0.1.3
- jukebox-0.2.7
- minisat-0.1.2
- structural-induction-0.3
- twee-0.1

flags:
    tip-spec: {stack: True}
    tip-haskell-frontend: {stack: True}
