resolver: lts-6.5
packages:
- tip-haskell-frontend/
- tip-lib/
- tip-spec/
- location:
   git: git://github.com/nick8325/quickspec
   commit: a01d9aa35eac311562db9e1ef22ddc5514020654

extra-deps:
- genifunctors-0.3
- ghc-simple-0.1.3
- jukebox-0.2.7
- minisat-0.1.2
- structural-induction-0.3
- twee-0.1

flags:
    tip-spec: {stack: True}
