resolver: lts-10.3

packages:
- tip-types/
- tip-lib/
- tip-ghc/
- tip-spec/
- tip-prelude/
- location:
    git: git://github.com/nick8325/quickspec
    commit: 6fe847f6f5b2a8df8797586631b9544b16f93944
  extra-dep: true
extra-deps:
- jukebox-0.3.5
- minisat-0.1.2
- structural-induction-0.3
- twee-lib-2.1.5
- genifunctors-0.4
- stm-promise-0.0.3.1
- constraints-0.9.1
- spoon-0.3.1
- testing-feat-0.4.0.3
- tagshare-0.0
flags:
    tip-spec: {stack: True}
    tip-ghc: {stack: True}
